#!/usr/bin/env bash

setup_tmpdir() {
    local repodir=$1
    local tmp_dir=$2

    # Move files to a tmp folder
    mkdir -p "$tmp_dir/sources"

    local tmp_archive="$tmp_dir/git_archive.tar.gz"
    git -C "$repodir" ls-files | xargs tar -C "$repodir" -czf "$tmp_archive"
    tar xzf "$tmp_archive" -C "$tmp_dir/sources"
    rm "$tmp_archive"
}

build_package() {
    local tmp_dir=$1
    local debian_codename=$2
    local debug=$3
    local arch=$4

    local opts=(
        --dist "$debian_codename"
        --no-run-lintian
        --no-run-piuparts
        --no-run-autopkgtest
    )
    if [[ "$debug" == "debug" ]]; then
        opts+=(--anything-failed-commands='%s')
    fi
    if [[ "$arch" != "all" ]]; then
        opts=(--host "$arch")
    fi

    # Actual build is running here!
    pushd "$tmp_dir/sources" >/dev/null || exit 1
        sbuild "${opts[@]}"
    popd >/dev/null || exit 1
}

distribute_package() {
    local tmp_dir=$1
    local repo_dir=$2
    local debian_codename=$3
    local package=$4
    local version=$5
    local branch=$6
    local arch=$7

    reprepro --waitforlock 6 \
        --basedir "$repo_dir" \
        --component "$branch" \
        include "$debian_codename" \
        "$root_dir/${package}_${version}_${arch}.changes"

}
