#!/usr/bin/env bash

CHROOT_PREINSTALLS=(
    aptitude
    build-essential
    ccache
    cmake
    debhelper
    debhelper
    devscripts
    dh-python
    eatmydata
    git
    libidn11-dev
    liblua5.1-0-dev
    libssl-dev
    lua5.1
    perl-openssl-defaults
    python3-all
    python3-jinja2
    python3-psutil
    python3-setuptools
    python3-yaml
    quilt
    txt2man
    wget
)

# Temporary fix to run on @repo
CHROOT_SUFFIX="-sbuild-vinaigrette2"

get_chroot_name() {
    local dist=$1
    echo "$dist$CHROOT_SUFFIX"
}

make_chroot() {
    local dist=$1

    local chroot_dir="$CHROOTS_DIR/$dist-all"
    if [ ! -d "$chroot_dir" ]; then
        info "Creating chroot for Debian ${dist}..."
        mkdir -p "$(dirname "$chroot_dir")"
        sbuild-createchroot --chroot-suffix="$CHROOT_SUFFIX" --include="${CHROOT_PREINSTALLS[*]}" "$dist" "$chroot_dir"
    fi
}
