#!/usr/bin/env bash

PACKAGES=(yunohost yunohost-admin yunohost-portal moulinette SSOwat)

declare -A PROJECT_URLS=(
    [yunohost]=https://github.com/yunohost/yunohost
    [yunohost-admin]=https://github.com/yunohost/yunohost-admin
    [yunohost-portal]=https://github.com/yunohost/yunohost-portal
    [moulinette]=https://github.com/yunohost/moulinette
    [SSOwat]=https://github.com/yunohost/SSOwat
)

declare -A DEBIAN_VERSIONS=(
    [11]="bullseye"
    [12]="bookworm"
    [13]="trixie"
)

declare -A PROJECT_BRANCHES=(
    [bookworm]="dev"
    [trixie]="trixie"
)
