#!/usr/bin/env bash

array_print_sep() {
    local sep=$1
    shift
    local tmpvar
    printf -v tmpvar '%s'"$sep" "$@"
    printf '%s' "${tmpvar%"$sep"}"
}


array_contains_element() {
    local e match="$1"
    shift
    for e; do
        if [[ "$e" == "$match" ]]; then
            return 0
        fi
    done
    return 1
}

is_already_running() {
    local scriptname
    scriptname=$(basename "$0")
    local pidfile="/tmp/$scriptname"

    if [ -f "$pidfile" ]; then
        pid=$(cat "$pidfile")
        if ps -p "$pid" > /dev/null 2>&1; then
            return 0
        else
            echo "Cleaning up stale PID file..."
            rm "$pidfile"
        fi
    fi

    echo "$$" > "$pidfile"
    return 1
}

cleanup_pidfile() {
    local scriptname
    scriptname=$(basename "$0")
    local pidfile="/tmp/$scriptname"

    if [ -f "$pidfile" ]; then
        pid=$(cat "$pidfile")
        if [ "$$" == "$pid" ]; then
            rm "$pidfile"
        else
            echo "warning: pidfile touched by someone else ?!"
        fi
    else
        echo "warning: pidfile vanished ?!"
    fi
}
