#!/bin/bash

# Identity

DEBSIGN_KEYID=59A3E6FF
DEBFULLNAME="YunoHost Contributors"
DEBEMAIL="contrib@yunohost.org"
MAIL="rebuildd@yunohost.org"
REPO_URL="repo.yunohost.org"

# Codenames, components and architectures

AVAILABLE_CODENAMES="jessie stretch"
AVAILABLE_COMPONENTS="stable testing unstable extra"
AVAILABLE_ARCH="amd64 i386 armhf"

DEFAULT_CODENAME="jessie"
DEFAULT_COMPONENT="unstable"
DEFAULT_ARCH="amd64"

# Folders...

HOME_VINAIGRETTE="/home/vinaigrette"
GIT_REPOS="$HOME_VINAIGRETTE/repos/"
BUILD_DEB="$HOME_VINAIGRETTE/build_deb"

PBUILDER_HOME="$HOME_VINAIGRETTE/pbuilder/"
PBUILDER_IMAGES="$PBUILDER_HOME/images/"
PBUILDER_RESULTS="$PBUILDER_HOME/result/"
DAILY_PACKAGES="$PBUILDER_HOME/packages/"
REPO_DIR=/var/www/repo/debian
PATATE_REPO_DIR=/var/www/repo/patate

# Scripts

BUILD_SOURCES="$PBUILDER_HOME/build-sources"
INCLUDE_CHANGES="$HOME_VINAIGRETTE/repo/include-changes"
SENDXMPP="$HOME_VINAIGRETTE/sendxmpp"


