#!/bin/bash

# Identity

DEBSIGN_KEYID=59A3E6FF
DEBFULLNAME="YunoHost Contributors"
DEBEMAIL="contrib@yunohost.org"
MAIL="rebuildd@yunohost.org"
REPO_URL="vinaigrette.yunohost.org"

# Codenames, components and architectures

AVAILABLE_CODENAMES="jessie stretch"
AVAILABLE_COMPONENTS="stable testing unstable extra"
AVAILABLE_ARCH="amd64 i386 armhf"

DEFAULT_CODENAME="jessie"
DEFAULT_COMPONENT="unstable"
DEFAULT_ARCH="amd64"

# Folders...

HOME_VINAIGRETTE="/home/vinaigrette"
GIT_REPOS="$HOME_VINAIGRETTE/gitrepos/"
REPO_DIR=/var/www/repo/debian

PBUILDER_HOME="$HOME_VINAIGRETTE/scripts/pbuilder/"
PBUILDER_IMAGES="$HOME_VINAIGRETTE/images/"
PBUILDER_RESULTS="$PBUILDER_HOME/result"
DAILY_PACKAGES="$PBUILDER_HOME/packages/"
PBUILDER_CONF="$PBUILDER_HOME/config/pbuilder/"

# Scripts

BUILD_SOURCES="$PBUILDER_HOME/build-sources"
BUILD_DEB="$HOME_VINAIGRETTE/scripts/build_deb"
INCLUDE_CHANGES="$HOME_VINAIGRETTE/scripts/repo/include-changes"


