#!/bin/sh

#
# Dirty hook to npm install, because I have no idea how this
# is supposed to be done properly
# (no network during the actual build)
#

PACKAGEJSON=$(find /build/ -name "package.json")
if [ ! -z "$PACKAGEJSON" ]
then
echo "======================================================"
/usr/bin/apt-get install git nodejs -y
mkdir /nonexistent
chown pbuilder:pbuilder /nonexistent
echo "========================"
echo "Starting npm install ..."
echo "========================"
cd $(dirname $PACKAGEJSON) && su pbuilder -c "npm install"
echo "======================================================"
fi
