#!/bin/sh

#
# Dirty hook to npm install, because I have no idea how this
# is supposed to be done properly
# (no network during the actual build)
#

if ls -d /build/yunohost-admin* >dev/null 2>&1
then
	echo "========================"
	echo "Starting npm install ..."
	echo "========================"
	mkdir /nonexistent
	chown pbuilder:pbuilder /nonexistent
	cd /build/yunohost-admin*/app
	su pbuilder -c "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin npm --progress false ci"
fi

