#!/bin/bash

PKG_PATH=$1

apt-get -q update

cd $PKG_PATH

echo "--------------------------------"
echo "Installing build-dependencies..."

mk-build-deps -i -r -t "apt-get --no-install-recommends -y" || exit 1
rm -f *build-deps*_all.deb

echo "--------------------------------"
echo "Creating source package..."

# Creating source package without signing it
debuild -S -sa -uc

# Be sure to clean directory
debclean
