#!/bin/bash

PKG_PATH=$1

apt-get -q update

cd $PKG_PATH

echo "--------------------------------"
echo "Installing build-dependencies..."

LOG="/var/log/mk-build-deps.log"
mk-build-deps -i -t "apt-get --no-install-recommends -y" >> $LOG 2>&1 \
  || { echo "mk-build-deps failed, logs are in $LOG"; exit 1; }
rm -f *build-deps*_all.deb

echo "--------------------------------"
echo "Creating source package..."

# Creating source package without signing it
debuild --no-lintian -S -sa -uc

# Be sure to clean directory
debclean
